name: pusher_client
description: |
  A Pusher Channels client plugin for Flutter targeting Android and iOS. It
  wraps pusher-websocket-java v2.4.0 and PusherSwift v10.1.0.
version: 2.1.3
homepage: https://github.com/chinloyal/pusher_client
documentation: https://github.com/chinloyal/pusher_client/blob/master/README.md


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.chinloyal.pusher_client
        pluginClass: PusherClientPlugin
      ios:
        pluginClass: PusherClientPlugin
